[package]
name = "testdata-rt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path-slash = "0.2.1"
thiserror = "1.0.33"
utime = "0.3.1"
walkdir = "2.3.2"
