[package]
name = "e2e"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
testdata = { path = "../.." }

[features]
e2e = []
